import { useState, useEffect } from "react";
import {
  Settings, Calendar, Smartphone, Percent, Bell, Save, RefreshCw,
  CheckCircle2, X, Building2, Shield, Lock, FileText, Check
} from "lucide-react";
import {
  billingStore, type BillingSettingsConfig
} from "./billingData";

interface BillingSettingsPageProps {
  onNavigate?: (page: string) => void;
}

export function BillingSettingsPage({ onNavigate }: BillingSettingsPageProps) {
  const [settings, setSettings] = useState<BillingSettingsConfig>(billingStore.getSettings());
  const [toast, setToast] = useState("");

  useEffect(() => {
    return billingStore.subscribe(() => {
      setSettings(billingStore.getSettings());
    });
  }, []);

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(""), 3500); };

  const handleSave = () => {
    billingStore.setSettings(settings);
    showToast("Billing settings, Payment Gateway configurations & notification templates saved!");
  };

  const inputStyle = {
    background: "var(--muted)",
    border: "1px solid var(--border)",
    fontSize: 13,
    color: "var(--foreground)",
  };

  return (
    <div className="p-6">
      {/* ── Header ──────────────────────────────────────────────────────────── */}
      <div className="flex items-center justify-between mb-5">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h1 style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 22, color: "var(--foreground)" }}>
              Billing Configuration & Gateways
            </h1>
            <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold" style={{ background: "#DCFCE7", color: "#16A34A" }}>
              Live System Settings
            </span>
          </div>
          <p style={{ fontSize: 13, color: "var(--muted-foreground)" }}>
            Billing cycles, automated invoicing rules, MFS gateways (bKash/Nagad), BTRC VAT compliance & SMS alerts
          </p>
        </div>

        <button
          onClick={handleSave}
          className="flex items-center gap-2 px-4 py-2 rounded-lg text-white font-medium shadow-sm transition-all"
          style={{ background: "var(--primary)", fontSize: 13 }}
        >
          <Save size={14} /> Save All Settings
        </button>
      </div>

      {/* ── Settings Grid ────────────────────────────────────────────────────── */}
      <div className="grid gap-6" style={{ gridTemplateColumns: "1fr 1fr" }}>
        {/* Section 1: Billing Cycle & Auto-Invoicing */}
        <div className="rounded-xl p-5 space-y-4" style={{ background: "var(--card)", border: "1px solid var(--border)" }}>
          <div className="flex items-center gap-2 mb-2 pb-2 border-b border-border">
            <Calendar size={18} className="text-primary" />
            <h3 style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 16, color: "var(--foreground)" }}>
              Billing Cycle & Auto-Invoicing
            </h3>
          </div>

          <div className="space-y-3.5">
            <div>
              <label style={{ fontSize: 11, fontWeight: 600, color: "var(--muted-foreground)", display: "block", marginBottom: 5 }}>
                BILLING MODEL & RECURRING CYCLE
              </label>
              <select
                value={settings.billingCycleType}
                onChange={e => setSettings(s => ({ ...s, billingCycleType: e.target.value }))}
                className="w-full px-3 py-2 rounded-lg outline-none text-xs"
                style={inputStyle}
              >
                <option value="calendar_month">Prepaid Calendar Month (1st to 30/31st)</option>
                <option value="anniversary">Anniversary Date Cycle (Date-to-Date)</option>
                <option value="postpaid_metered">Postpaid Monthly Consumption</option>
              </select>
            </div>

            <div>
              <label style={{ fontSize: 11, fontWeight: 600, color: "var(--muted-foreground)", display: "block", marginBottom: 5 }}>
                INVOICE AUTO-GENERATION SCHEDULE
              </label>
              <select
                value={settings.autoGenerateDate}
                onChange={e => setSettings(s => ({ ...s, autoGenerateDate: e.target.value }))}
                className="w-full px-3 py-2 rounded-lg outline-none text-xs"
                style={inputStyle}
              >
                <option value="1st of every month">1st of Every Month at 00:01 AM</option>
                <option value="25th of previous month">25th of Previous Month (Advance Bill)</option>
                <option value="28th of previous month">28th of Previous Month</option>
              </select>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div>
                <label style={{ fontSize: 11, fontWeight: 600, color: "var(--muted-foreground)", display: "block", marginBottom: 5 }}>
                  INVOICE PREFIX
                </label>
                <input
                  value={settings.invoicePrefix}
                  onChange={e => setSettings(s => ({ ...s, invoicePrefix: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg outline-none font-mono text-xs"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={{ fontSize: 11, fontWeight: 600, color: "var(--muted-foreground)", display: "block", marginBottom: 5 }}>
                  DEFAULT DUE WINDOW (DAYS)
                </label>
                <input
                  type="number"
                  value={settings.dueDaysOffset}
                  onChange={e => setSettings(s => ({ ...s, dueDaysOffset: Number(e.target.value) }))}
                  className="w-full px-3 py-2 rounded-lg outline-none font-mono text-xs"
                  style={inputStyle}
                />
              </div>
            </div>

            <div className="pt-2 space-y-2">
              <label className="flex items-center gap-2 cursor-pointer text-xs">
                <input
                  type="checkbox"
                  checked={settings.autoDisconnectOnMikrotik}
                  onChange={e => setSettings(s => ({ ...s, autoDisconnectOnMikrotik: e.target.checked }))}
                  className="rounded accent-primary"
                />
                <span>Sync overdue clients directly to MikroTik address-list (<code>{settings.mikrotikAddressList}</code>)</span>
              </label>
            </div>
          </div>
        </div>

        {/* Section 2: Payment Gateways Integration */}
        <div className="rounded-xl p-5 space-y-4" style={{ background: "var(--card)", border: "1px solid var(--border)" }}>
          <div className="flex items-center gap-2 mb-2 pb-2 border-b border-border">
            <Smartphone size={18} className="text-pink-600" />
            <h3 style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 16, color: "var(--foreground)" }}>
              Payment Gateway Integration
            </h3>
          </div>

          {/* bKash */}
          <div className="p-3.5 rounded-xl border border-border space-y-3" style={{ background: "var(--muted)" }}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-pink-500" />
                <span className="font-bold text-sm text-foreground">bKash Merchant Checkout API</span>
              </div>
              <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-emerald-100 text-emerald-700">
                LIVE CONNECTED
              </span>
            </div>
            <div className="grid grid-cols-2 gap-2 text-xs">
              <div>
                <span className="text-muted-foreground block text-[10px]">MERCHANT NUMBER</span>
                <input
                  value={settings.bkashMerchantId}
                  onChange={e => setSettings(s => ({ ...s, bkashMerchantId: e.target.value }))}
                  className="w-full px-2 py-1.5 rounded outline-none font-mono text-xs bg-card border border-border"
                />
              </div>
              <div>
                <span className="text-muted-foreground block text-[10px]">APP KEY</span>
                <input
                  value={settings.bkashAppKey}
                  onChange={e => setSettings(s => ({ ...s, bkashAppKey: e.target.value }))}
                  className="w-full px-2 py-1.5 rounded outline-none font-mono text-xs bg-card border border-border"
                />
              </div>
            </div>
            <button
              onClick={() => showToast("bKash Webhook IPN ping verified successfully (HTTP 200 OK)!")}
              className="text-xs text-primary font-medium hover:underline flex items-center gap-1"
            >
              <RefreshCw size={11} /> Test bKash API Connection
            </button>
          </div>

          {/* Nagad */}
          <div className="p-3.5 rounded-xl border border-border space-y-3" style={{ background: "var(--muted)" }}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="w-2.5 h-2.5 rounded-full bg-amber-500" />
                <span className="font-bold text-sm text-foreground">Nagad Direct Gateway</span>
              </div>
              <span className="px-2 py-0.5 rounded text-[11px] font-semibold bg-emerald-100 text-emerald-700">
                ACTIVE
              </span>
            </div>
            <div className="grid grid-cols-2 gap-2 text-xs">
              <div>
                <span className="text-muted-foreground block text-[10px]">MERCHANT ID</span>
                <input
                  value={settings.nagadMerchantId}
                  onChange={e => setSettings(s => ({ ...s, nagadMerchantId: e.target.value }))}
                  className="w-full px-2 py-1.5 rounded outline-none font-mono text-xs bg-card border border-border"
                />
              </div>
              <div>
                <span className="text-muted-foreground block text-[10px]">PUBLIC KEY</span>
                <input
                  defaultValue="••••••••••••••••"
                  type="password"
                  className="w-full px-2 py-1.5 rounded outline-none font-mono text-xs bg-card border border-border"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Section 3: Taxes, VAT & BTRC Compliance */}
        <div className="rounded-xl p-5 space-y-4" style={{ background: "var(--card)", border: "1px solid var(--border)" }}>
          <div className="flex items-center gap-2 mb-2 pb-2 border-b border-border">
            <Percent size={18} className="text-emerald-600" />
            <h3 style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 16, color: "var(--foreground)" }}>
              Taxes, VAT & BTRC Compliance
            </h3>
          </div>

          <div className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label style={{ fontSize: 11, fontWeight: 600, color: "var(--muted-foreground)", display: "block", marginBottom: 5 }}>
                  TELECOM VAT RATE (%)
                </label>
                <input
                  type="number"
                  value={settings.vatRate}
                  onChange={e => setSettings(s => ({ ...s, vatRate: Number(e.target.value) }))}
                  className="w-full px-3 py-2 rounded-lg outline-none font-mono text-xs"
                  style={inputStyle}
                />
              </div>
              <div>
                <label style={{ fontSize: 11, fontWeight: 600, color: "var(--muted-foreground)", display: "block", marginBottom: 5 }}>
                  VAT BIN NUMBER
                </label>
                <input
                  value={settings.vatBin}
                  onChange={e => setSettings(s => ({ ...s, vatBin: e.target.value }))}
                  className="w-full px-3 py-2 rounded-lg outline-none font-mono text-xs"
                  style={inputStyle}
                />
              </div>
            </div>

            <div className="space-y-2 pt-2">
              <label className="flex items-center gap-2 cursor-pointer text-xs">
                <input
                  type="checkbox"
                  checked={settings.priceTaxInclusive}
                  onChange={e => setSettings(s => ({ ...s, priceTaxInclusive: e.target.checked }))}
                  className="rounded accent-primary"
                />
                <span>Package prices are Inclusive of 5% VAT (BTRC tariff standard)</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer text-xs">
                <input
                  type="checkbox"
                  defaultChecked
                  className="rounded accent-primary"
                />
                <span>Auto-calculate 1% Social Obligation Fund (SOF) & 5.5% BTRC Revenue Share in monthly finance report</span>
              </label>
            </div>
          </div>
        </div>

        {/* Section 4: Automated Billing SMS & Notifications */}
        <div className="rounded-xl p-5 space-y-4" style={{ background: "var(--card)", border: "1px solid var(--border)" }}>
          <div className="flex items-center gap-2 mb-2 pb-2 border-b border-border">
            <Bell size={18} className="text-amber-500" />
            <h3 style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 16, color: "var(--foreground)" }}>
              Automated SMS Reminders
            </h3>
          </div>

          <div className="space-y-3 text-xs">
            <div className="p-3 rounded-lg border border-border bg-muted flex items-center justify-between">
              <div>
                <strong className="block text-foreground">Invoice Generated SMS</strong>
                <span className="text-muted-foreground text-[11px]">Sent on 1st of month with invoice bill amount & bKash pay link</span>
              </div>
              <input
                type="checkbox"
                checked={settings.sendSmsOnGenerate}
                onChange={e => setSettings(s => ({ ...s, sendSmsOnGenerate: e.target.checked }))}
                className="rounded accent-primary"
              />
            </div>

            <div className="p-3 rounded-lg border border-border bg-muted flex items-center justify-between">
              <div>
                <strong className="block text-foreground">3 Days Before Due Reminder</strong>
                <span className="text-muted-foreground text-[11px]">Gentle reminder before late fee grace period starts</span>
              </div>
              <input
                type="checkbox"
                checked={settings.sendSmsOnDue}
                onChange={e => setSettings(s => ({ ...s, sendSmsOnDue: e.target.checked }))}
                className="rounded accent-primary"
              />
            </div>

            <div className="p-3 rounded-lg border border-border bg-muted flex items-center justify-between">
              <div>
                <strong className="block text-foreground">Instant Payment Confirmation SMS</strong>
                <span className="text-muted-foreground text-[11px]">Instant receipt text with Transaction ID & thank you note</span>
              </div>
              <input
                type="checkbox"
                checked={settings.sendSmsOnPaid}
                onChange={e => setSettings(s => ({ ...s, sendSmsOnPaid: e.target.checked }))}
                className="rounded accent-primary"
              />
            </div>
          </div>

          <div className="pt-2">
            <button
              onClick={handleSave}
              className="w-full py-2.5 rounded-lg text-white font-medium text-xs shadow-sm flex items-center justify-center gap-2"
              style={{ background: "var(--primary)" }}
            >
              <Save size={14} /> Save All Billing Configurations
            </button>
          </div>
        </div>
      </div>

      {/* ── Toast ───────────────────────────────────────────────────────────── */}
      {toast && (
        <div
          className="fixed bottom-6 right-6 z-[300] flex items-center gap-3 px-5 py-3.5 rounded-xl shadow-2xl"
          style={{ background: "#130606", color: "#ffffff", fontSize: 13, fontWeight: 500 }}
        >
          <CheckCircle2 size={16} style={{ color: "#4ADE80" }} />
          <span>{toast}</span>
          <button onClick={() => setToast("")} className="ml-2 hover:opacity-75">
            <X size={14} style={{ color: "rgba(255,255,255,0.6)" }} />
          </button>
        </div>
      )}
    </div>
  );
}
