// ─── Interfaces ─────────────────────────────────────────────────────────────

export interface Invoice {
  id: string;
  customer: string;
  custId: string;
  phone: string;
  zone: string;
  pkgName: string;
  subtotal: number;
  vat: number;
  discount: number;
  amount: number;
  period: string;
  issued: string;
  due: string;
  status: "paid" | "pending" | "overdue" | "cancelled";
  method: string | null;
  paidAt?: string;
  trxId?: string;
}

export interface Payment {
  id: string;
  customer: string;
  custId: string;
  invoice: string;
  amount: number;
  method: "bKash" | "Nagad" | "Bank" | "Cash" | "SSLCommerz" | "Rocket";
  txn: string;
  date: string;
  time: string;
  addedBy: string;
  channel: string;
  status: "verified" | "pending" | "refunded";
  notes?: string;
}

export interface IspPackage {
  id: string;
  name: string;
  down: number;
  up: number;
  price: number;
  type: "PPPoE" | "Static IP" | "DHCP" | "Hotspot" | "Corporate Lease";
  customers: number;
  margin: number;
  mikrotikProfile: string;
  burstLimit: string;
  fupLimit: string;
  status: "active" | "archived";
}

export interface DiscountRule {
  id: string;
  code: string;
  name: string;
  type: "percentage" | "fixed";
  value: number;
  scope: "all" | "new_customers" | "resellers" | "specific_pkg" | "annual_plan";
  minPackageSpeed?: number;
  durationMonths: number;
  usageCount: number;
  maxUsage: number;
  validUntil: string;
  status: "active" | "expired" | "paused";
}

export interface CustomerAdjustment {
  id: string;
  customer: string;
  custId: string;
  type: "waiver" | "promotional" | "goodwill" | "late_fee" | "reconnection_charge";
  nature: "discount" | "penalty";
  amount: number;
  reason: string;
  ticketId?: string;
  approvedBy: string;
  date: string;
  status: "applied" | "reverted";
}

export interface BillingSettingsConfig {
  billingCycleType: string;
  autoGenerateDate: string;
  dueDaysOffset: number;
  vatEnabled: boolean;
  vatRate: number;
  vatBin: string;
  priceTaxInclusive: boolean;
  invoicePrefix: string;
  receiptPrefix: string;
  nextSequence: string;
  companyName: string;
  companyPhone: string;
  companyEmail: string;
  companyAddress: string;
  bkashLive: boolean;
  bkashMerchantId: string;
  bkashAppKey: string;
  bkashAppSecret: string;
  nagadLive: boolean;
  nagadMerchantId: string;
  sslCommerzLive: boolean;
  sslStoreId: string;
  sendSmsOnGenerate: boolean;
  sendSmsOnDue: boolean;
  sendSmsOnPaid: boolean;
  autoDisconnectOnMikrotik: boolean;
  mikrotikAddressList: string;
}

import { REAL_ISP_CUSTOMERS, REAL_BILLING_PAYMENTS } from "../../data/realIspData";

// ─── Real ISP Invoices & Payments Seeded from Excel ───────────────────────────

export const INITIAL_INVOICES: Invoice[] = REAL_ISP_CUSTOMERS.flatMap(c => {
  return (c.invoices || []).map(inv => {
    const isPaid = inv.status === "paid";
    const isSep = (inv.month || "").includes("September");
    return {
      id: inv.id,
      customer: c.name,
      custId: c.clientCode || c.id,
      phone: c.phone,
      zone: c.zone || "DHAKA DIVISION",
      pkgName: c.package || "20Mbps",
      subtotal: inv.amount || c.price || 500,
      vat: 0,
      discount: 0,
      amount: inv.amount || c.price || 500,
      period: inv.month || (isSep ? "September 2026" : "August 2026"),
      issued: isSep ? "01 Sep 2026" : "01 Aug 2026",
      due: inv.dueDate || (isSep ? "10 Sep 2026" : "10 Aug 2026"),
      status: isPaid ? ("paid" as const) : ("overdue" as const),
      method: isPaid ? (inv.paymentMethod || "bKash") : null,
      paidAt: inv.paidDate || (isPaid ? (isSep ? "01 Sep 2026" : "05 Aug 2026") : undefined),
      trxId: inv.trxId
    };
  });
});

export const INITIAL_PAYMENTS: Payment[] = REAL_BILLING_PAYMENTS;

export const INITIAL_PACKAGES: IspPackage[] = [
  { id: "PKG-01", name: "10 Mbps Basic", down: 10, up: 5, price: 600, type: "PPPoE", customers: 1, margin: 75, mikrotikProfile: "profile-10M-5M", burstLimit: "15M/8M 15s", fupLimit: "Unlimited", status: "active" },
  { id: "PKG-02", name: "20 Mbps Fiber Standard", down: 20, up: 10, price: 800, type: "PPPoE", customers: 0, margin: 78, mikrotikProfile: "profile-20M-10M", burstLimit: "25M/12M 15s", fupLimit: "Unlimited", status: "active" },
  { id: "PKG-03", name: "30 Mbps Home Fiber", down: 30, up: 15, price: 1000, type: "PPPoE", customers: 0, margin: 80, mikrotikProfile: "profile-30M-15M", burstLimit: "40M/20M 20s", fupLimit: "Unlimited", status: "active" },
  { id: "PKG-04", name: "50 Mbps Ultra Fiber Pro", down: 50, up: 25, price: 1200, type: "PPPoE", customers: 1, margin: 82, mikrotikProfile: "profile-50M-25M", burstLimit: "70M/35M 20s", fupLimit: "Unlimited", status: "active" },
  { id: "PKG-05", name: "100 Mbps Gigabit Fiber", down: 100, up: 50, price: 2000, type: "PPPoE", customers: 0, margin: 85, mikrotikProfile: "profile-100M-50M", burstLimit: "120M/60M 20s", fupLimit: "Unlimited", status: "active" },
];

export const INITIAL_DISCOUNT_RULES: DiscountRule[] = [
  { id: "DISC-101", code: "SUMMER2026", name: "Summer Speed Boost", type: "percentage", value: 15, scope: "specific_pkg", minPackageSpeed: 20, durationMonths: 3, usageCount: 1, maxUsage: 500, validUntil: "31 Aug 2026", status: "active" },
  { id: "DISC-102", code: "REFERFRIEND", name: "Referral Bonus Credit", type: "fixed", value: 200, scope: "all", durationMonths: 1, usageCount: 0, maxUsage: 500, validUntil: "30 Sep 2026", status: "active" },
];

export const INITIAL_ADJUSTMENTS: CustomerAdjustment[] = [];

export const INITIAL_BILLING_SETTINGS: BillingSettingsConfig = {
  billingCycleType: "calendar_month",
  autoGenerateDate: "1st of every month",
  dueDaysOffset: 10,
  vatEnabled: true,
  vatRate: 5,
  vatBin: "BIN-002918274-0102",
  priceTaxInclusive: true,
  invoicePrefix: "INV-",
  receiptPrefix: "REC-",
  nextSequence: "10205",
  companyName: "MAA BEST NETWORK Broadband Ltd.",
  companyPhone: "+880 9611-223344",
  companyEmail: "billing@maabestnetwork.com",
  companyAddress: "Holding 12, Main Road, Block B, Dhaka, Bangladesh",
  bkashLive: true,
  bkashMerchantId: "01700998877",
  bkashAppKey: "bkash_live_k99214a8x",
  bkashAppSecret: "••••••••••••••••••••••••",
  nagadLive: true,
  nagadMerchantId: "6829104",
  sslCommerzLive: false,
  sslStoreId: "maabest_live_01",
  sendSmsOnGenerate: true,
  sendSmsOnDue: true,
  sendSmsOnPaid: true,
  autoDisconnectOnMikrotik: true,
  mikrotikAddressList: "blocked_unpaid_users",
};

// ─── Simple In-Memory / LocalStorage Store ───────────────────────────────────

let sharedInvoices = [...INITIAL_INVOICES];
let sharedPayments = [...INITIAL_PAYMENTS];
let sharedPackages = [...INITIAL_PACKAGES];
let sharedDiscounts = [...INITIAL_DISCOUNT_RULES];
let sharedAdjustments = [...INITIAL_ADJUSTMENTS];
let sharedSettings = { ...INITIAL_BILLING_SETTINGS };

const listeners = new Set<() => void>();
function notify() {
  listeners.forEach(cb => cb());
}

export const billingStore = {
  getInvoices: () => sharedInvoices,
  setInvoices: (invs: Invoice[]) => { sharedInvoices = invs; notify(); },
  addInvoice: (inv: Invoice) => { sharedInvoices = [inv, ...sharedInvoices]; notify(); },

  getPayments: () => sharedPayments,
  setPayments: (pays: Payment[]) => { sharedPayments = pays; notify(); },
  addPayment: (pay: Payment) => {
    sharedPayments = [pay, ...sharedPayments];
    // Mark matching invoice as paid
    sharedInvoices = sharedInvoices.map(i => i.id === pay.invoice ? { ...i, status: "paid", method: pay.method, paidAt: pay.date, trxId: pay.txn } : i);
    notify();
  },

  getPackages: () => sharedPackages,
  setPackages: (pkgs: IspPackage[]) => { sharedPackages = pkgs; notify(); },
  addPackage: (pkg: IspPackage) => { sharedPackages = [...sharedPackages, pkg]; notify(); },
  updatePackage: (pkg: IspPackage) => { sharedPackages = sharedPackages.map(p => p.id === pkg.id ? pkg : p); notify(); },

  getDiscounts: () => sharedDiscounts,
  setDiscounts: (rules: DiscountRule[]) => { sharedDiscounts = rules; notify(); },
  addDiscount: (rule: DiscountRule) => { sharedDiscounts = [rule, ...sharedDiscounts]; notify(); },

  getAdjustments: () => sharedAdjustments,
  setAdjustments: (adjs: CustomerAdjustment[]) => { sharedAdjustments = adjs; notify(); },
  addAdjustment: (adj: CustomerAdjustment) => { sharedAdjustments = [adj, ...sharedAdjustments]; notify(); },

  getSettings: () => sharedSettings,
  setSettings: (s: BillingSettingsConfig) => { sharedSettings = s; notify(); },

  subscribe: (cb: () => void) => {
    listeners.add(cb);
    return () => {
      listeners.delete(cb);
    };
  }
};
